/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class urbetter_usbcam_UsbCamControl */

#ifndef _Included_urbetter_usbcam_UsbCamControl
#define _Included_urbetter_usbcam_UsbCamControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     urbetter_usbcam_UsbCamControl
 * Method:    CamOpen
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_urbetter_usbcam_UsbCamControl_CamOpen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     urbetter_usbcam_UsbCamControl
 * Method:    CamClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_urbetter_usbcam_UsbCamControl_CamClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     urbetter_usbcam_UsbCamControl
 * Method:    CamGetWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_urbetter_usbcam_UsbCamControl_CamGetWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     urbetter_usbcam_UsbCamControl
 * Method:    CamGetHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_urbetter_usbcam_UsbCamControl_CamGetHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     urbetter_usbcam_UsbCamControl
 * Method:    CamGetData
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_urbetter_usbcam_UsbCamControl_CamGetData
  (JNIEnv *, jclass, jint);


#ifdef __cplusplus
}
#endif
#endif
